### ISSUE TITLE
instructions?

### ISSUE THREAD

**Issue by csells** [ncave/dotnet-js#20]
Are there instructions for building, running and extending?

For context, I'm interested in playing around with this project as an extension of Blazor and also because I'm unable to get the Blazor source to run on a box with VS2017 15.4. Thoughts about the latter would be appreciated as well.

**Comment by ncave** [comment]
@csells Since you mention VS2017 I'm going to take a wild guess that you're running on Windows, so building is just running the `build.cmd` (after you clone the repo). I'll add more scripts to simplify building on other platforms.

- Running in Node.js: `node ./wwwroot/out/bundle.js`
- Running in Browser: `npm start` to start a web server, then go to `localhost:5000`
   (hint: look in the Console output)

You can also open/run in VS Code, just pick a debug config and hit F5. The Chrome debugger add-on is highly recommended, but optional.

Extending at this point is mainly about fixing outstanding DNA issues, the DNA runtime (JIT) solution is in the src/DNA folder. Please note that adding every missing BCL class to DNA is probably not what Blazor needs, as they're trying to keep it small (I'm guessing).

**Comment by csells** [comment]
Thanks. I was able to figure out how to get it running with build.cmd and node's http-server.

**Comment by ncave** [comment]
Added instruction to readme.
